// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/Blog/BlogPostCategory.tsx";
import * as $$$1 from "./loaders/Blog/BlogPostCategoryPath.tsx";
import * as $$$2 from "./loaders/Blog/CategoryList.tsx";
import * as $$$$$$0 from "./sections/BlogPost.tsx";
import * as $$$$$$1 from "./sections/BlogPosts.tsx";
import * as $$$$$$2 from "./sections/Companies.tsx";
import * as $$$$$$3 from "./sections/Data.tsx";
import * as $$$$$$4 from "./sections/Differences.tsx";
import * as $$$$$$5 from "./sections/Faq.tsx";
import * as $$$$$$6 from "./sections/Footer.tsx";
import * as $$$$$$7 from "./sections/Form.tsx";
import * as $$$$$$8 from "./sections/Header.tsx";
import * as $$$$$$9 from "./sections/Hero.tsx";
import * as $$$$$$10 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$11 from "./sections/Logos.tsx";
import * as $$$$$$12 from "./sections/MainPost.tsx";
import * as $$$$$$13 from "./sections/Operation.tsx";
import * as $$$$$$14 from "./sections/Testimonials.tsx";
import * as $$$$$$15 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/Blog/BlogPostCategory.tsx": $$$0,
    "site/loaders/Blog/BlogPostCategoryPath.tsx": $$$1,
    "site/loaders/Blog/CategoryList.tsx": $$$2,
  },
  "sections": {
    "site/sections/BlogPost.tsx": $$$$$$0,
    "site/sections/BlogPosts.tsx": $$$$$$1,
    "site/sections/Companies.tsx": $$$$$$2,
    "site/sections/Data.tsx": $$$$$$3,
    "site/sections/Differences.tsx": $$$$$$4,
    "site/sections/Faq.tsx": $$$$$$5,
    "site/sections/Footer.tsx": $$$$$$6,
    "site/sections/Form.tsx": $$$$$$7,
    "site/sections/Header.tsx": $$$$$$8,
    "site/sections/Hero.tsx": $$$$$$9,
    "site/sections/ImageWithParagraph.tsx": $$$$$$10,
    "site/sections/Logos.tsx": $$$$$$11,
    "site/sections/MainPost.tsx": $$$$$$12,
    "site/sections/Operation.tsx": $$$$$$13,
    "site/sections/Testimonials.tsx": $$$$$$14,
    "site/sections/Theme/Theme.tsx": $$$$$$15,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
